const HEBREW_PRONUNCIATION_SYMBOL_CARDS = [
  {
    id: 1,
    symbol: "\u05b8",
    name: "Qamats",
    transliteration: "qamats",
    simpleSound: "ah as in father",
    example: "\u05d0\u05b8",
    explanation: "A small T shaped mark under the letter. It usually makes an \"ah\" sound.",
    memoryPicture: "It sits under the letter like an open mouth saying \"ah.\"",
    category: "vowel",
    audio: null
  },
  {
    id: 2,
    symbol: "\u05b7",
    name: "Patach",
    transliteration: "patach",
    simpleSound: "ah as in father",
    example: "\u05d0\u05b7",
    explanation: "A small line under the letter. It usually makes an \"ah\" sound.",
    memoryPicture: "A flat little mouth opening under the letter.",
    category: "vowel",
    audio: null
  },
  {
    id: 3,
    symbol: "\u05b6",
    name: "Segol",
    transliteration: "segol",
    simpleSound: "eh as in bed",
    example: "\u05d0\u05b6",
    explanation: "Three small dots under the letter. It usually makes an \"eh\" sound.",
    memoryPicture: "Three little seeds making a short \"eh\" sound.",
    category: "vowel",
    audio: null
  },
  {
    id: 4,
    symbol: "\u05b5",
    name: "Tsere",
    transliteration: "tsere",
    simpleSound: "ay as in they, or eh depending on tradition",
    example: "\u05d0\u05b5",
    explanation: "Two side by side dots under the letter. It often makes an \"ay\" or long \"eh\" sound.",
    memoryPicture: "Two little eyes looking up and saying \"ay.\"",
    category: "vowel",
    audio: null
  },
  {
    id: 5,
    symbol: "\u05b4",
    name: "Hiriq",
    transliteration: "hiriq",
    simpleSound: "ee as in machine",
    example: "\u05d0\u05b4",
    explanation: "One small dot under the letter. It usually makes an \"ee\" sound.",
    memoryPicture: "One tiny dot makes a tiny \"ee\" sound.",
    category: "vowel",
    audio: null
  },
  {
    id: 6,
    symbol: "\u05b9",
    name: "Holam",
    transliteration: "holam",
    simpleSound: "oh as in go",
    example: "\u05d0\u05b9",
    explanation: "A dot above the letter. It usually makes an \"oh\" sound.",
    memoryPicture: "The sound rises up like \"oh!\"",
    category: "vowel",
    audio: null
  },
  {
    id: 7,
    symbol: "\u05bb",
    name: "Qubuts",
    transliteration: "qubuts",
    simpleSound: "oo as in moon",
    example: "\u05d0\u05bb",
    explanation: "Three diagonal dots under the letter. It usually makes an \"oo\" sound.",
    memoryPicture: "Three drops of water saying \"oo.\"",
    category: "vowel",
    audio: null
  },
  {
    id: 8,
    symbol: "\u05b0",
    name: "Sheva",
    transliteration: "sheva",
    simpleSound: "very short sound or silent",
    example: "\u05d0\u05b0",
    explanation: "Two vertical dots under the letter. Sometimes it makes a tiny quick sound and sometimes it is silent.",
    memoryPicture: "Two quiet footsteps under the letter.",
    category: "vowel/helper",
    audio: null
  },
  {
    id: 9,
    symbol: "\u05bc",
    name: "Dagesh",
    transliteration: "dagesh",
    simpleSound: "hardens or strengthens a letter",
    example: "\u05d1\u05bc",
    explanation: "A dot inside the letter. It can make some letters sound harder, like bet instead of vet.",
    memoryPicture: "A little power button inside the letter.",
    category: "pronunciation mark",
    audio: null
  },
  {
    id: 10,
    symbol: "\u05e9\u05c1",
    name: "Shin Dot",
    transliteration: "shin dot",
    simpleSound: "sh",
    example: "\u05e9\u05c1",
    explanation: "A dot on the upper right side of the letter shin. It makes the \"sh\" sound.",
    memoryPicture: "Right side means \"shhhh.\"",
    category: "pronunciation mark",
    audio: null
  },
  {
    id: 11,
    symbol: "\u05e9\u05c2",
    name: "Sin Dot",
    transliteration: "sin dot",
    simpleSound: "s",
    example: "\u05e9\u05c2",
    explanation: "A dot on the upper left side of the letter shin/sin. It makes the \"s\" sound.",
    memoryPicture: "Left side slides into \"s.\"",
    category: "pronunciation mark",
    audio: null
  }
];
